<?php

namespace gframework\adminBundle\Repository;

/**
 * noticiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class noticiasRepository extends \Doctrine\ORM\EntityRepository
{
}
