noticias_index:
    path:     /
    defaults: { _controller: "adminBundle:noticias:index" }
    methods:  GET

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "adminBundle:noticias:show" }
    methods:  GET

noticias_new:
    path:     /new
    defaults: { _controller: "adminBundle:noticias:new" }
    methods:  [GET, POST]

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "adminBundle:noticias:edit" }
    methods:  [GET, POST]

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "adminBundle:noticias:delete" }
    methods:  DELETE
    
    
noticias_deletar:
    path:     /{id}/deletar
    defaults: { _controller: "adminBundle:noticias:deletar" }
    methods:  [GET, POST]

